### ISSUE TITLE
The driver takes exclusive ownership of the SPI bus, which is a shared resource.

### ISSUE THREAD

**Issue by eparmstrong** [Finomnis/st7565#8]
The SPI bus is designed to be used with multiple chips.  In my case I wish to read font data from a different chip before writing it to the st7565. I imagine this working like:

(spi, disp) = st7565.into_graphics_mode_release_spi();
disp.flush(&mut spi);

The st7564 struct should maintain ownership of the CS and DC pins, as they are what lets st7564 maintain it's state.

This does mess with display_interface, and the st7564 does have two different interfaces, SPI and parallel, and it would be nice to not have to deal with that inside st7565.

If it's something you think is doable, but you don't have time, I could work on it.
If it's something you don't want in st7565 I can go do my own thing.

**Comment by Finomnis** [comment]
I think instead of making this a responsibility of this library, it would be better to implement a shared SPI object. Something based on `RefCell`. Might experiment around a little and post some code when I find a solution.

**Comment by eparmstrong** [comment]
That sounds like a useful abstraction. In the long run I'm going to want a driver that does both st7565 and the 20L16S1Y font library.  It would be nice to reuse your st7565 library, and having a ref based SPI api would let me do that, but I will worry about that later.  Lots of other things to do before I need a LCD.

**Comment by Finomnis** [comment]
My API is already trait based, it should be as simple as implementing said trait for a ref based SPI struct. Might pay some code here in the next couple of days, if I get to it.

**Comment by Finomnis** [comment]
Here is one possible solution, maybe it fits your usecase. It uses `RefCell` combined with a newtype wrapper I called `SharedSPI` that propagates the `spi::Write` functionality out of the `RefCell`.

Note that now, the `spi` variable in `main()` is reusable and you can create multiple `SharedSPI(&spi)`.

**SAFETY**: `RefCell` prevents multi-threaded access to it, so it's kind of safe. The only protection it doesn't have is of course that the CS/DC pins could be in the wrong state when the communication happens (like: the pins for device A are already set, and then device B does a communication, accidentally delivering data to A). The compiler can't do anything about this, this is the programmer's responsibility. But it should be easy to verify as only the single-threaded case is possible. So `SPIInterface`, for example, is trivially provably correct, because it sets the pins, does the communication and restores the pins while staying in one function. So nothing in the single-threaded case can interrupt it.

```rust
#![no_main]
#![no_std]

use core::cell::RefCell;

use defmt_rtt as _; // global logger
use nrf52840_hal as hal; // memory layout
use panic_probe as _;

use display_interface_spi::SPIInterface;
use embedded_graphics::{
    geometry::Size,
    mono_font::{ascii::FONT_8X13, MonoTextStyle},
    pixelcolor::BinaryColor,
    prelude::*,
    primitives::{Circle, PrimitiveStyle, Rectangle},
    text::Text,
};
use embedded_hal::blocking::spi;
use hal::gpio::Level;
use st7565::{displays::DOGM132W5, ST7565};

// same panicking *behavior* as `panic-probe` but doesn't print a panic message
// this prevents the panic message being printed *twice* when `defmt::panic` is invoked
#[defmt::panic_handler]
fn panic() -> ! {
    cortex_m::asm::udf()
}

/// Terminates the application and makes `probe-run` exit with exit-code = 0
pub fn exit() -> ! {
    loop {
        cortex_m::asm::bkpt();
    }
}

struct SharedSPI<'a, SPI>(&'a RefCell<SPI>);

impl<SPI> spi::Write<u8> for SharedSPI<'_, SPI>
where
    SPI: spi::Write<u8>,
{
    type Error = SPI::Error;
    fn write(&mut self, words: &[u8]) -> Result<(), Self::Error> {
        self.0.borrow_mut().write(words)
    }
}

#[cortex_m_rt::entry]
fn main() -> ! {
    let peripherals = hal::pac::Peripherals::take().unwrap();
    let port0 = hal::gpio::p0::Parts::new(peripherals.P0);
    let port1 = hal::gpio::p1::Parts::new(peripherals.P1);

    // Create timer
    let mut timer = hal::timer::Timer::new(peripherals.TIMER0);

    // Get DOGM132W-5 pins
    let mut disp_rst = port0.p0_12.into_push_pull_output(Level::High);
    let disp_cs = port1.p1_09.into_push_pull_output(Level::High).degrade();
    let disp_a0 = port0.p0_23.into_push_pull_output(Level::High).degrade();
    let disp_scl = port0.p0_21.into_push_pull_output(Level::High).degrade();
    let disp_si = port0.p0_19.into_push_pull_output(Level::Low).degrade();

    // Create DOGM132W-5 spi bus
    let spi = RefCell::new(hal::Spim::new(
        peripherals.SPIM0,
        hal::spim::Pins {
            sck: Some(disp_scl),
            mosi: Some(disp_si),
            miso: None,
        },
        hal::spim::Frequency::M8,
        hal::spim::MODE_3,
        0,
    ));
    let disp_spi = SPIInterface::new(SharedSPI(&spi), disp_a0, disp_cs);

    // Create DOGM132W-5 display driver
    let mut disp = ST7565::new(disp_spi, DOGM132W5).into_graphics_mode();
    disp.reset(&mut disp_rst, &mut timer).unwrap();
    disp.flush().unwrap();
    disp.set_display_on(true).unwrap();

    // Draw content
    Circle::new(Point::new(6, 6), 20)
        .into_styled(PrimitiveStyle::with_stroke(BinaryColor::On, 2))
        .draw(&mut disp)
        .unwrap();
    Rectangle::new(Point::new(106, 6), Size::new(20, 20))
        .into_styled(PrimitiveStyle::with_stroke(BinaryColor::On, 2))
        .draw(&mut disp)
        .unwrap();
    let font = MonoTextStyle::new(&FONT_8X13, BinaryColor::On);
    Text::new("Hello,\nRust!", Point::new(43, 13), font)
        .draw(&mut disp)
        .unwrap();

    // Send content to display
    disp.flush().unwrap();

    // Done
    loop {}
}
```

Does this solve your problem?

**Comment by eparmstrong** [comment]
This should work for what I am doing and is enough to close the issue.

As you note, this places 95% of the responsibility onto the programmer. I think bumping things up to a ref->option->spi in the display interface would move it to about 80% runtime checking, but I'm not going to bother with this right now.  The whole point of me working on this now, is giving my self a break from working on things where if I mess up it will cost more then $1000.  If I some how turn up the boost voltage to x11 and fry a $3 board, then that's on me.

**Comment by Finomnis** [comment]
I thought about how I could incorporate it in my design, but it doesn't seem too easy. I'm not sure if you realized, but I never use the SPI directly, I only use the `SPIInterface`, which owns both the actual SPI bus as also the CS and DC pins. So even if I gave it back to you, you would still need to rip it apart again before being able to use it. And whatever other library you use to talk to the memory chip would have to support this as well.

If you have an example of how other libraries deal with this, feel free to post it. I'm open to API changes, as long as they aren't awkward.

The `SPIInterface` object isn't something I wrote, just so you realize. It's from the [`display_interface_spi`](https://docs.rs/display-interface-spi/latest/display_interface_spi/struct.SPIInterface.html) crate. It does support a `release()` method, however, so if I were to give it back to you you could destructure it and re-use the SPI bus. It would be quite awkward to juggle the CS and DC pins, though. It also might require me to do some major rework of the driver. I'm not opposed, though. let me think about this more, I'm fine if we keep this issue open.

**Comment by eparmstrong** [comment]
It's a good API that covers 98% of the use cases perfectly. The other 2% can spend the time to fix it for their case, if they want. If I do a release for the board, combining the font chip and the display, I will probably encapsulate and not worry about supporting additional chips on the SPI bus, too.

**Comment by Finomnis** [comment]
Actually, after thinking about it, it might be quite easy. I don't initially do anything wth the `SPIInterface` object, so I could simply remove it from `ST7565::new`. I would then have to add it to `into_raw_mode()` (because raw mode definitely needs it) and then to `flush()` of the graphics mode as `&mut SPIInterface`. That's all the places it is used right now.

Then you can have some user object that manages the SPI bus and creates the `SPIInterface` on the fly when necessary.

**Comment by Finomnis** [comment]
There would still be the problem that `SPIInterface` needs to own them and can't simply accept `&mut` values, which would require moving things back and forth, which sucks. I am thinking about requesting a change in `display_interface_spi`, but implementation seems tricky. It's quite hard to specify a generic so that it in the end can deal with `&mut T` and `T` both.

**Comment by Finomnis** [comment]
I might suggest a new `BorrowedSPIInterface` struct that borrows them. That should make implementing a SPI bus manager object much easier, otherwise all those checks would have to be done at runtime by moving the spi bus object in and out of `Option`s, which sucks, imo.

**Comment by eparmstrong** [comment]
While I look forward to what you come up with, you do have a very clean interface for most people.  Although that may change as more Chinese/Japanese people start using Rust as having a font chip on the same bus as the display makes perfect sense for them.

**Comment by Finomnis** [comment]
Let me propose a change and have you review it. Might take a while though, not sure if I get to it today.

**Comment by Finomnis** [comment]
Hm. Turns out it is harder after all. `common_functionality.rs` also uses it, I forgot about that one.

**Comment by Finomnis** [comment]
Well, turns out I did find the time :)

What's your opinion?

I managed to bake it all into the type state, no `Option` anywhere :)
Although that might mean that the entire display buffer gets moved whenever the bus is assigned/released, not sure how performance critical this is. My feeling is that it should be fine.

This would be mitigated by putting it on the heap or a global variable or a user-allocated buffer, but it isn't easily possible to manage it within the driver itself as long as I'm using type state and no allocator exists.

**Comment by eparmstrong** [comment]
The API looks clean.  The exact behavior of the state transition looks like something that could be compiler settings dependent.  
The compile time behavior is what I was hoping for.  I want to work out how to use a debugger on this chip and see exactly what happens at run time, but it may be a few days to never until I get to it.

**Comment by Finomnis** [comment]
I'm working on something, but I this one actually does seem more complicated.

**Comment by eparmstrong** [comment]
I hooked up both the LCD and the font chip to the same SPI interface and my test code is working.  Releasing and attaching the display interface isn't the most ergonomic, but I really like the type safety it brings, and I think it's good to have it as an option.

**Comment by Finomnis** [comment]
@eparmstrong Sorry, I was busy last week.

What do you think about this? https://github.com/Finomnis/st7565/pull/10/files

I split the page buffer into a separate variable, and now the example looks like this:
```rust
    let mut page_buffer = GraphicsPageBuffer::new();
    let mut disp = ST7565::new(disp_spi, DOGM132W5).into_graphics_mode(&mut page_buffer);
```

This means that the state no longer carries the page buffer, but only a mutable reference to it. Therefore, switching between normal and detached graphics mode will no longer perform a page buffer copy.

Opinions?

**Comment by eparmstrong** [comment]
This does take care of the copy.  I don't like the extra step to set up the
buffer, but this is no_std and allocation is the user's responsibility. So
I don't see a way around that.

**Comment by Finomnis** [comment]
Strongly related: https://github.com/therealprof/display-interface/pull/33

Together with this and the changes to my crate, it should be trivial to write an SPI bus manager.

**Comment by Finomnis** [comment]
Sorry, this auto-closed. I'd like to keep it open until https://github.com/therealprof/display-interface/pull/33 is merged and I created an example based on it.

**Comment by Finomnis** [comment]
@eparmstrong A discussion in the `display-interface` crate resulted in the realization that a **lot** changes with `embedded-hal 1.0.0`. They now introduced the concept of `SPIBus` vs `SPIDevice` which allows for multiple SPI devices on one bus without all of this juggling around. It's not released yet, though, `embedded-hal` is currently in `1.0.0-alpha.9`. So given the amount of change this goes through it might be wise to wait for the release. `display-interface` is also already preparing for the release, as with the change, they need to adjust their API as well.

**Comment by Finomnis** [comment]
@eparmstrong I implemented an example of an SPI Bus Manager, based on borrowing newtype wrappers.
What do you think? Does that help your usecase? https://github.com/Finomnis/st7565/tree/main/examples/nrf52840_dogm132w5_graphics_with_shared_bus.rs
